<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<fieldset class="fieldset create account" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')); ?>">
    <legend class="legend"><span><?= $block->escapeHtml(__('Additional Information')) ?></span></legend>
    <br/>
    <div class="field github_url required">
        <label for="github_url" class="label">
            <span><?= $block->escapeHtml(__('Github URL')); ?></span>
        </label>
        <div class="control">
            <input type="text" name="github_url" id="github_url"
                   title="<?= $block->escapeHtmlAttr(__('Github URL')); ?>" class="input-text"
                   data-validate="{required:true,'validate-url':true}" autocomplete="off">
        </div>
    </div>
</fieldset>
